# Generated by Django 2.1.dev20171207141032 on 2017-12-29 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('eventType', models.CharField(max_length=100)),
                ('deck', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opp_deck', models.CharField(max_length=100)),
                ('game1', models.IntegerField(default=0)),
                ('game2', models.IntegerField(default=0)),
                ('game3', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtgrecords.Event')),
            ],
        ),
    ]
