# Generated by Django 2.1.dev20171207141032 on 2017-12-31 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtgrecords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventType',
            new_name='event_type',
        ),
    ]
